package main

var _headerTemplate = `
// Code generated by $GOPATH/src/github.com/namelessup/bilibili/app/tool/cache/mc. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated mc cache package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	"fmt"
	{{if .UseStrConv}}"strconv"{{end}}
	{{if .EnableBatch }}"sync"{{end}}
NEWLINE
	"github.com/namelessup/bilibili/library/stat/prom"
	{{if .UseMemcached }}"github.com/namelessup/bilibili/library/cache/memcache"{{end}}
	{{if .EnableBatch }}"github.com/namelessup/bilibili/library/sync/errgroup"{{end}}
	"github.com/namelessup/bilibili/library/log"
	{{.ImportPackage}}
)

var _ _mc
`
